### ISSUE TITLE
Add option to open and pin tabs automatically

### ISSUE THREAD

**Issue by rhldr** [gauntface/pin-it-extension#522]
For my work machine, I have several sites that need to be opened and pinned. I would love an option to automatically open and pin URLs upon initial Chrome opening or when this extension is loaded.

**Comment by gauntface** [comment]
Just to check I understand - when a new window is opened (or browser first opens), you'd like your pinned tabs to be opened automatically (no need to click the icon)?

I did try this a long time ago in an old extension and I ran into some inconsistency, but I can look into adding this as a setting and work on that as issues crop up.

**Comment by rhldr** [comment]
Yes. Perhaps it would be simpler with an option to open and pin configured
tab(s) when the extension loads?

On Friday, Aug 9, 2024, 2:06 PM, wrote:

> Just to check I understand - when a new window is opened (or browser
first opens), you'd like your pinned tabs to be opened automatically (no
need to click the icon)? I did try this a long time ago in an old extension
and I ran into some inconsistency, but I can look into adding this as a
setting and work on that as issues crop up. -- Reply to this email directly
or view it on GitHub:
https://github.com/gauntface/pin-it-extension/issues/522#issuecomment-2278662677
You are receiving this because you authored the thread. Message ID:
Richard Holder
Experienced Marketing Professional
801 376 8982 (cell)
www.linkedin.com/in/richardeholder
<http://www.linkedin.com/in/richardeholder>

**Comment by gauntface** [comment]
Did some work on this and think I came up something that works. The major gotcha is the workaround to account for this issue: https://stackoverflow.com/questions/67806779/im-getting-an-error-tabs-cannot-be-edited-right-now-user-may-be-dragging-a-ta

The problem is that a new window can be made via Menu > New Window (or Ctrl + N) or by dragging a tab. When you drag a tag, a new window event is fired, but you can't set tabs on the window until the user has finished dragging the window.

For now, I try and open the pinned tabs, if it fails, I wait 100ms, check if the window still exists, if so, try to open the pinned tabs again and I do that in a loop for a maximum of 5 minutes.

From my experiments this seems to work well, but because this is a workaround for a bad/odd Chrome behavior, I've labelled the feature experimental for now.

![Screenshot from 2024-08-11 15-03-49](https://github.com/user-attachments/assets/40e0ff9c-84b7-4f2f-b69d-c7b8c67b39a9)

**Comment by gauntface** [comment]
Should be published in `v4.0.0` of the extension

**Comment by gauntface** [comment]
Release was approved over the weekend. @rhldr let me know if this works for you.

**Comment by rhldr** [comment]
Awesome, thank you so much!   I'll put it through it's paces this week and
confirm.

**Comment by rhldr** [comment]
Working very well, thank you.

**Comment by gauntface** [comment]
Had to roll back the change due to a bug, likely something small I missed. Will fix it and upload a new version tonight.

**Comment by gauntface** [comment]
4.0.2 should have the fix

**Comment by gauntface** [comment]
Just tested and everything looks good.
